services:
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
     - ./.env
    volumes:
      - ./data:/app/data
    # working_dir: /app
    ports:
      - 8501:8501
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:8501/_stcore/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
